### ISSUE TITLE
Request for  Experimental Results

### ISSUE THREAD

**Issue by kai0416s** [RhoHenning/INR-PCC#3]
Thank you for your excellent open-source work.

I noticed your README, but it seems that the experimental results for geometry and attributes are currently not available. 

Could you please provide the experimental results for each sequence in an Excel file? This would allow us to fairly compare your method with others. 

Thank you.

**Comment by RhoHenning** [comment]
Hello,

I've preserved the data that I use to plot the R-D curves for 8iVFB in the paper (but any other results are not preserved). The Excel file is attached [here](https://github.com/user-attachments/files/17493664/result.xlsx). I hope this will be helpful.

**Comment by kai0416s** [comment]
Thank you, this will be sufficient.
